image: Visual Studio 2019
init:
  - git config --global core.autocrlf true
branches:
  only:
    - main
build_script:
  - ps: |
      dotnet cake build.cake --bootstrap
      dotnet cake build.cake --pack
assembly_info:
  # No thank you, I'll do this myself
  patch: false
# We'll run the tests in the build script
test: off
# AppVeyor will create a release tag if a matching one does not exist
# hence triggering another build
skip_tags: true
skip_commits:
  files:
    - .editorconfig
    - LICENSE
    - README.md
    - docs/*
# Environment variables
environment:
  # No need to pre-warm the `NuGet` cache
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
# `install` will run before `build_script`
install:
  # `dotnet-decode-base-64` is targeting `net6.0`, so we can safely install the latest `SDK`
  # The `SDK` is required to restore, build, publish... a `.NET` application
  # https://www.microsoft.com/net/download/windows
  - ps: .\setup\dotnet-install.ps1 -Channel Current -InstallDir 'C:\Program Files\dotnet\'
  - ps: dotnet tool restore
for:
-
  branches:
    except:
      - main
  deploy:
    - provider: GitHub
      # By convention release versions start with `v`
      release: v$(APPVEYOR_BUILD_VERSION)
      auth_token:
        # Encrypted `GitHub` `PAT`
        # https://www.appveyor.com/docs/deployment/github/#provider-settings
        secure: XM4FoPiy2XjubFQwXRD6xcUxHHnx2URaeMlrwRF4gcgA/obNTO/TjUXiv7yUMiNH
      artifact: transform,packages
      draft: false
      prerelease: true
-
  branches:
    only:
      - main
  deploy:
    - provider: GitHub
      # By convention release versions start with `v`
      release: v$(APPVEYOR_BUILD_VERSION)
      auth_token:
        # Encrypted `GitHub` `PAT`
        # https://www.appveyor.com/docs/deployment/github/#provider-settings
        secure: XM4FoPiy2XjubFQwXRD6xcUxHHnx2URaeMlrwRF4gcgA/obNTO/TjUXiv7yUMiNH
      artifact: transform,packages
      draft: false
      prerelease: false
    - provider: NuGet
      server: https://www.nuget.org/api/v2/package
      api_key:
        # Encrypted `NuGet.org` token - https://www.nuget.org/account/ApiKeys
        # https://www.appveyor.com/docs/deployment/nuget/#provider-settings
        secure: TcV2BC6PH+wTkgn+wXMJ4152K798oPZg196YGqNN5ZzYl9XRcFHK+kp/pkbiBC1J
      skip_symbols: false
      symbol_server: https://nuget.smbsrc.net/
      artifact: packages
